// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASDGFVMn-dhzRaux3EQx3xdvgmvDiD0e0',
    appId: '1:171439893771:web:c138355c48a57faa0d460e',
    messagingSenderId: '171439893771',
    projectId: 'taradventapp',
    authDomain: 'taradventapp.firebaseapp.com',
    storageBucket: 'taradventapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfyydQOJ2K2RCUijC3ZRcccl9D46NqQi0',
    appId: '1:171439893771:android:28eb43c3ca0d64400d460e',
    messagingSenderId: '171439893771',
    projectId: 'taradventapp',
    storageBucket: 'taradventapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_RSNyyxxLm97iSzThTvDN7t34pCE8oY',
    appId: '1:171439893771:ios:00eb787e2ab4cc5e0d460e',
    messagingSenderId: '171439893771',
    projectId: 'taradventapp',
    storageBucket: 'taradventapp.appspot.com',
    iosClientId:
        '171439893771-2ft4iudtidemd2ihm12mj3dojlbumcg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taradventapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_RSNyyxxLm97iSzThTvDN7t34pCE8oY',
    appId: '1:171439893771:ios:00eb787e2ab4cc5e0d460e',
    messagingSenderId: '171439893771',
    projectId: 'taradventapp',
    storageBucket: 'taradventapp.appspot.com',
    iosClientId:
        '171439893771-2ft4iudtidemd2ihm12mj3dojlbumcg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taradventapp',
  );
}
